version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 23
    commands:
      - cd frontend
      - npm install

  build:
    commands:
      - npm run build
      - cd ../backend
      - npm install

artifacts:
  files:
    - backend/**/*
    - frontend/dist/**/*
