version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 23
    commands:
      - cd frontend
      - npm ci

  build:
    commands:
      - npm run build

artifacts:
  base-directory: frontend/dist
  files:
    - "**/*"
