version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - cd frontend
      - npm ci

  build:
    commands:
      - npm run build
      - ls -la dist # DEBUG LINE (important)

artifacts:
  base-directory: frontend/dist
  files:
    - "**/*"
